@startuml
'https://plantuml.com/sequence-diagram

autonumber "<b>Шаг 00:"
skinparam maxMessageSize 200

actor "Пользователь" as user

box FRONT
boundary "WEB/iOS/Android" as front
end box

box BACKEND #LightGreen
participant "Платформа интернет банкинга" as platform
participant "АБС\nмастер система по договорам" as abs
participant "CRM\nмастер система по клиентам" as crm
participant "ESB" as esb
participant "CCS \nПродуктовая система кредитных карт" as css
participant "Карточный процессинг\nмастер система по картам" as cards
end box

legend
Не сталкивался с банковским процессингом, поэтому мои предположения:
Платформа интернет банкинга - некий Gateway для взаимодействия с клиентскими приложениями
АБС - сервис, отвечающий за заключение договоров
CRM - сервис, хранящий клиентскую информацию, туда же "засунул" аналитику по платежеспособнояти и надежности
ESB - корпоративная шина данных
CCS - сервис отвечающий за продукт кредитных карт
Карточный процессинг - сервис, отражающий выпуск "пластика"
end legend

user -> front: В личном кабинете запрашивает выпуск кредитной карты, указывает необходдимые параметры (лимит/% и т.д.)
front -> platform: Запрос на выпуск кредитной карты
== Процесс подписания договора синхронный, чтобы не отпускать клиента ==
activate platform
user <- front : Форма ожидания выполнения операции
platform -> abs : Инициация создания нового кредитного договора
activate abs
abs -> crm : Проверка клиентской информации для заключения договора
activate crm
crm -> crm : Бодбор действующих документов, анкетные данные, платежеспособность, надежность
abs <-- crm : Список действующих документов, анкетные данные клиента, платежеспособность, надежность
deactivate crm
abs -> abs : Проверка соответствия клиента для заключения договора
alt Чего-то не хватает
    platform <-- abs : Чек-лист проверки для уточнения у клиента
    front <-- platform : Чек-лист проверки для уточнения у клиента
    user <-- front : Форма уточнения у клиента
    user -> front : Уточненные данные
    front -> platform : Уточненные данные
    platform -> abs : Уточненные данные
    group Корректировка данных клиента (асинхронно)
        platform ->> esb : Сообщение об изменении/дополнении клиентской информации
        esb ->> crm : Сообщение об изменении/дополнении клиентской информации
        activate crm
        crm -> crm :Обновление/дополнениt клиентской информации
        deactivate crm
    end group
abs -> abs : Проверка соответствия клиента для заключения договора
else Проверка пройдена успешно
    platform <-- abs : Договор для подписания клиентом
    deactivate abs
    front <-- platform : Договор для подписания клиентом
    user <-- front : Форма подписания клиентом договора
    user -> front : Подтверждение клиентом договора на выпуск кредитной карты
    front -> platform : Запрос на заключение договора по кредитной карте
    user <-- front : Подтверждение инициации выпуска кредитной карты, перевод в ЛК с обещанием уведомить об окончании процедуры
    == Дальше процесс выпуска карты асинхронный ==
    platform ->> abs : Запрос на создание нового кредитного договора
    deactivate platform
    activate abs
    abs -> abs : Заведение и подписание договора, открытие счета
    abs ->> esb : Сообщение о подписании нового договора с кредитной картой
    deactivate abs
    esb ->> platform : Сообщение о подписании нового договора с кредитной картой
    activate platform
    platform -> front : Сообщение о подписании нового договора с кредитной картой
    deactivate platform
    front -> user : Уведомление о подписании договора и начале открытия счета кредитной карты
    esb ->> css : Сообщение о подписании нового договора с кредитной картой
    activate css
    css ->> css : Инициациализация выпуска кредитной карты, связка счетов расхода/пополнения
    css ->> esb : Сообщение об открытии новых счетов под кредитную карту
    deactivate css
    esb ->> platform : Сообщение об открытии новых счетов под кредитную карту
    activate platform
    platform -> front : Сообщение об открытии новых счетов под кредитную карту
    deactivate platform
    front -> user : Уведомление об открытии новых счетов под кредитную карту и возможности расплачиваться ей с телефона
    esb ->> cards : Сообщение об открытии новых счетов под кредитную карту
    activate cards
        cards ->> cards : Выпуск новой пластиково карты
        cards ->> esb : Сообщение о готовности пластиковой карты
    deactivate cards
    esb ->> platform : Сообщение о готовности пластиковой карты
    activate platform
    platform -> front : Сообщение о готовности пластиковой карты
    deactivate platform
    front -> user : Уведомление о готовности пластиковой карты и приглашение забрать ее в офисе банка

end
deactivate crm
alt <font color=red> Ошибка аутентификации

@enduml